# Generated by Django 2.2.12 on 2021-09-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20210902_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título')),
                ('dia', models.IntegerField(blank=True, null=True, verbose_name='Plazos de Pago')),
                ('tiemp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiempo Diferido')),
                ('desc', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Descuento %')),
                ('tipo', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Credito')], max_length=10, verbose_name='Tipo de Pago')),
            ],
            options={
                'verbose_name': 'PriceList',
                'verbose_name_plural': 'PriceList',
                'ordering': ['id'],
            },
        ),
    ]
