# Generated by Django 2.2.12 on 2021-09-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_auto_20210907_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detalle',
            field=models.CharField(max_length=250, null=True, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='product',
            name='codigo',
            field=models.CharField(max_length=150, verbose_name='Referencia Interna'),
        ),
    ]
