# Generated by Django 2.2.12 on 2021-09-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_auto_20210907_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='serie',
        ),
    ]
