# Generated by Django 2.2.12 on 2021-09-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_quotationsale_quotationsaledetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotationsale',
            options={'default_permissions': (), 'ordering': ['-id'], 'permissions': (('view_quotationsale', 'Can view Solicitud de Ventas'), ('add_quotationsale', 'Can add Solicitud de  Ventas'), ('delete_quotationsale', 'Can delete Solicitud de Ventas')), 'verbose_name': 'Solicitud de Venta', 'verbose_name_plural': 'Solicitud de Ventas'},
        ),
    ]
