# Generated by Django 2.2.12 on 2021-09-09 13:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0011_auto_20210908_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='type_voucher',
            field=models.CharField(choices=[('ticket', 'Ticket'), ('factura', 'Factura')], default='factura', max_length=50),
        ),
        migrations.CreateModel(
            name='QuotationSaleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('dscto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total_dscto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.Sale')),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud de Venta',
                'verbose_name_plural': 'Detalle de Solicitud de Ventas',
                'ordering': ['-id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QuotationSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_condition', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Credito')], default='contado', max_length=50)),
                ('payment_method', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_debito_credito', 'Tarjeta de Debito / Credito'), ('efectivo_tarjeta', 'Efectivo y Tarjeta')], default='efectivo', max_length=50)),
                ('type_voucher', models.CharField(choices=[('ticket', 'Ticket'), ('factura', 'Factura')], default='ticket', max_length=50)),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('end_credit', models.DateField(default=datetime.datetime.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('dscto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total_dscto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('change', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('card_number', models.CharField(blank=True, max_length=30, null=True)),
                ('titular', models.CharField(blank=True, max_length=30, null=True)),
                ('amount_debited', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('entrada', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.Client')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plazo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.PriceList')),
            ],
            options={
                'verbose_name': 'Solicitudes de Venta',
                'verbose_name_plural': 'Solicitudes de Ventas',
                'ordering': ['-id'],
                'permissions': (('quotation_view_sale', 'Can view Solicitudes de Ventas'), ('quotation_add_sale', 'Can add Solicitudes de Ventas'), ('quotation_delete_sale', 'Can delete Solicitudes de Ventas')),
                'default_permissions': (),
            },
        ),
    ]
