# Generated by Django 2.2.12 on 2021-09-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_auto_20210909_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='serie',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Serie'),
        ),
    ]
