# Generated by Django 2.2.12 on 2021-09-09 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_sucursal_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='estado',
            field=models.CharField(choices=[('cotizacion', 'Cotización'), ('pedido', 'Pedido')], default='cotizacion', max_length=80),
        ),
        migrations.AddField(
            model_name='sale',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.Sucursal'),
        ),
    ]
