# Generated by Django 2.2.12 on 2021-09-09 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_auto_20210909_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sucursal',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.Sucursal'),
        ),
    ]
