# Generated by Django 2.2.12 on 2021-09-09 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_auto_20210909_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tval',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sucursal',
            field=models.ForeignKey(blank=True, default=8, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.Sucursal'),
        ),
    ]
