# Generated by Django 2.2.12 on 2021-09-09 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_auto_20210909_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='tval',
        ),
    ]
