# Generated by Django 2.2.12 on 2021-09-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_remove_sale_tval'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tval',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
