# Generated by Django 2.2.12 on 2021-09-10 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_sale_tval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='plazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.PriceList'),
        ),
    ]
