# Generated by Django 2.2.12 on 2021-09-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_auto_20210910_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='subtotaldos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
