# Generated by Django 2.2.12 on 2021-09-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0021_sale_subtotaldos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-id'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AlterModelOptions(
            name='saledetail',
            options={'ordering': ['-id'], 'verbose_name': 'Detalle de Venta', 'verbose_name_plural': 'Detalle de Ventas'},
        ),
        migrations.AlterField(
            model_name='sale',
            name='estado',
            field=models.CharField(choices=[('Cotización', 'Cotización'), ('Pedido', 'Pedido')], default='cotización', max_length=80),
        ),
    ]
