# Generated by Django 2.2.12 on 2021-09-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_auto_20210911_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='subtotaltres',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
