# Generated by Django 2.2.12 on 2021-09-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestdetail',
            name='dscto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='purchaserequestdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='purchaserequestdetail',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
