# Generated by Django 2.2.12 on 2021-09-15 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0026_auto_20210914_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.Sucursal'),
        ),
    ]
