# Generated by Django 2.2.12 on 2021-09-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0027_purchaserequest_sucursal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'default_permissions': (), 'ordering': ['-id'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='purchasedetail',
            options={'ordering': ['-id'], 'verbose_name': 'Detalle de Compra', 'verbose_name_plural': 'Detalle de Compras'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'default_permissions': (), 'ordering': ['-id'], 'verbose_name': 'Orden de Compra', 'verbose_name_plural': 'Ordenes de Compra'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderdetail',
            options={'ordering': ['-id'], 'verbose_name': 'Detalle de Compra', 'verbose_name_plural': 'Detalle de Compras'},
        ),
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'verbose_name': 'Solicitud de Compra', 'verbose_name_plural': 'Solicitudes de Compras'},
        ),
        migrations.AlterModelOptions(
            name='purchaserequestdetail',
            options={'ordering': ['-id'], 'verbose_name': 'Detalle de solicitud de Compra', 'verbose_name_plural': 'Detalle de solicitud de Compra'},
        ),
    ]
