# Generated by Django 2.2.12 on 2021-09-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0028_auto_20210915_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-id'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-id'], 'verbose_name': 'Orden de Compra', 'verbose_name_plural': 'Ordenes de Compra'},
        ),
    ]
