# Generated by Django 2.2.12 on 2021-09-15 19:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0029_auto_20210915_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='concepto',
            field=models.CharField(default=1, max_length=150, verbose_name='Concepto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='end_credit',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='payment_condition',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Credito')], default='contado', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pos.Provider'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
