# Generated by Django 2.2.12 on 2021-09-15 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0030_auto_20210915_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='plazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.Payment'),
        ),
    ]
