# Generated by Django 2.2.12 on 2021-09-15 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0031_purchaserequest_plazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='concepto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.Provider'),
        ),
    ]
