# Generated by Django 2.2.12 on 2021-09-15 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0032_auto_20210915_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'ordering': ['-id'], 'verbose_name': 'Solicitud de Compra', 'verbose_name_plural': 'Solicitudes de Compras'},
        ),
    ]
