# Generated by Django 2.2.12 on 2021-09-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0034_purchaserequest_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='dscto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='subtotaldos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='subtotaltres',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='total_dscto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='total_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
