# Generated by Django 2.2.12 on 2021-09-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0037_purchaserequest_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='payment_condition',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Credito')], default='credito', max_length=50),
        ),
    ]
