# Generated by Django 2.2.12 on 2021-09-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0038_auto_20210916_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='reference',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='state',
            field=models.CharField(choices=[('Enviado', 'Enviado'), ('Solicitud', 'Solicitud'), ('Anulado', 'Anulado'), ('Aprobado', 'Aprobado'), ('Asignar Series', 'Asignar Series'), ('Rechazado', 'Rechazado')], default='Enviado', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='state',
            field=models.CharField(choices=[('Enviado', 'Enviado'), ('Solicitud', 'Solicitud'), ('Anulado', 'Anulado'), ('Aprobado', 'Aprobado'), ('Asignar Series', 'Asignar Series'), ('Rechazado', 'Rechazado')], default='Enviado', max_length=50),
        ),
    ]
