# Generated by Django 2.2.12 on 2021-09-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0039_auto_20210916_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequestdetail',
            name='dscto',
        ),
    ]
