# Generated by Django 2.2.12 on 2021-09-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0040_remove_purchaserequestdetail_dscto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título')),
                ('porc', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Porcentaje %')),
            ],
            options={
                'verbose_name': 'Cards',
                'verbose_name_plural': 'Cards',
                'ordering': ['id'],
            },
        ),
    ]
