# Generated by Django 2.2.12 on 2021-09-17 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0041_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='recargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.Cards'),
        ),
    ]
