# Generated by Django 2.2.12 on 2021-09-18 19:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0044_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignaSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, max_length=150, null=True, verbose_name='Serie')),
                ('fechaPrevista', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Llegada')),
                ('cantped', models.IntegerField(default=0, verbose_name='Recibo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Product')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Provider')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Sucursal')),
            ],
            options={
                'verbose_name': 'AsignaSerie',
                'verbose_name_plural': 'AsignaSerie',
                'ordering': ['id'],
            },
        ),
    ]
