# Generated by Django 2.2.12 on 2021-09-18 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0045_asignaserie'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pos.Product'),
            preserve_default=False,
        ),
    ]
