# Generated by Django 2.2.12 on 2021-09-18 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0046_transfer_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='Contacto',
        ),
        migrations.AddField(
            model_name='transfer',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsable de envio'),
        ),
    ]
