# Generated by Django 2.2.12 on 2021-09-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0047_auto_20210918_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='employee',
        ),
        migrations.AddField(
            model_name='transfer',
            name='contacto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Solicitsante de Transferencia'),
        ),
    ]
