# Generated by Django 2.2.12 on 2021-09-18 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0048_auto_20210918_1247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
