# Generated by Django 2.2.12 on 2021-09-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0050_transferencias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transferencias',
        ),
    ]
