# Generated by Django 2.2.12 on 2021-09-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0052_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaserie',
            name='cantent',
            field=models.IntegerField(default=0, verbose_name='Recibo'),
        ),
        migrations.AlterField(
            model_name='asignaserie',
            name='cantped',
            field=models.IntegerField(default=0, verbose_name='Demanda'),
        ),
    ]
