# Generated by Django 2.2.12 on 2021-09-24 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0054_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stockmax',
            field=models.IntegerField(default=0, verbose_name='Stock Máximo'),
        ),
        migrations.AddField(
            model_name='product',
            name='stockmin',
            field=models.IntegerField(default=0, verbose_name='Stock Mínimo'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Provider', verbose_name='Proveedor'),
        ),
    ]
