# Generated by Django 2.2.12 on 2021-09-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0055_auto_20210924_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Mark',
                'verbose_name_plural': 'Mark',
                'ordering': ['id'],
            },
        ),
    ]
