# Generated by Django 2.2.12 on 2021-09-24 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0057_auto_20210924_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modelo',
            field=models.CharField(default=1, max_length=150, verbose_name='Modelo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.Mark', verbose_name='Marca'),
        ),
    ]
