# Generated by Django 2.2.12 on 2021-09-24 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0058_auto_20210924_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pos.Mark', verbose_name='Marca'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.Category', verbose_name='Categoría'),
        ),
    ]
