# Generated by Django 2.2.12 on 2021-09-28 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0060_auto_20210928_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaserie',
            name='numfactpro',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Serie'),
        ),
        migrations.CreateModel(
            name='TempSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, max_length=150, null=True, verbose_name='Serie')),
                ('cantped', models.IntegerField(default=0, verbose_name='Demanda')),
                ('cantrec', models.IntegerField(default=0, verbose_name='Recibo')),
                ('numfactpro', models.CharField(blank=True, max_length=150, null=True, verbose_name='Serie')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Product')),
            ],
            options={
                'verbose_name': 'AsignaSerie',
                'verbose_name_plural': 'AsignaSerie',
                'ordering': ['id'],
            },
        ),
    ]
