# Generated by Django 2.2.12 on 2021-09-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0061_auto_20210928_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempserie',
            name='numfactpro',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Número de Factura'),
        ),
    ]
