# Generated by Django 2.2.12 on 2021-09-28 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0062_auto_20210928_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tempserie',
            options={'ordering': ['id'], 'verbose_name': 'TempSerie', 'verbose_name_plural': 'TempSerie'},
        ),
    ]
