# Generated by Django 2.2.12 on 2021-09-28 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0063_auto_20210928_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesAsignarCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demanda', models.CharField(blank=True, max_length=30, null=True)),
                ('recibido', models.CharField(blank=True, max_length=30, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.Product')),
            ],
            options={
                'verbose_name': 'SeriesAsignarCompra',
                'verbose_name_plural': 'SeriesAsignarCompra',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SerieDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantrec', models.IntegerField(default=0)),
                ('nuserie', models.CharField(blank=True, max_length=150, null=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.SeriesAsignarCompra')),
            ],
            options={
                'verbose_name': 'Detalle de Serie',
                'verbose_name_plural': 'Detalle de Series',
                'ordering': ['-id'],
            },
        ),
    ]
