# Generated by Django 2.2.12 on 2021-09-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0064_seriedetail_seriesasignarcompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesasignarcompra',
            name='numfactpro',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
