# Generated by Django 2.2.12 on 2021-09-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0065_seriesasignarcompra_numfactpro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesasignarcompra',
            name='demanda',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Demanda'),
        ),
        migrations.AlterField(
            model_name='seriesasignarcompra',
            name='numfactpro',
            field=models.CharField(default=1, max_length=150, verbose_name='Número de Factura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seriesasignarcompra',
            name='product',
            field=models.CharField(max_length=150, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='seriesasignarcompra',
            name='recibido',
            field=models.CharField(default=1, max_length=30, verbose_name='Recibido'),
            preserve_default=False,
        ),
    ]
