# Generated by Django 2.2.12 on 2021-09-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0066_auto_20210928_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesasignarcompra',
            name='serie',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Serie'),
        ),
    ]
