# Generated by Django 2.2.12 on 2021-09-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0068_seriesasignarcompra_relacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriesasignarcompra',
            name='relacion',
        ),
    ]
