# Generated by Django 2.2.12 on 2021-09-29 18:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0069_remove_seriesasignarcompra_relacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Detalle de Transferencia',
                'verbose_name_plural': 'Detalle de Transferencias',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['-id'], 'verbose_name': 'Transferencia de Mercaderia', 'verbose_name_plural': 'Transferencias de Mercaderia'},
        ),
        migrations.RemoveField(
            model_name='asignaserie',
            name='numfactpro',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='fechaPrevista',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='fechaSalida',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='serie',
        ),
        migrations.AddField(
            model_name='operation',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Salida'),
        ),
        migrations.AddField(
            model_name='operation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operation',
            name='state',
            field=models.CharField(choices=[('Transferencia Realizada', 'Transferencia Realizada'), ('Transferencia Recibida', 'Transferencia Recibida')], default='Transferencia Realizada', max_length=50),
        ),
        migrations.DeleteModel(
            name='TempSerie',
        ),
        migrations.AddField(
            model_name='operationdetail',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.Operation'),
        ),
        migrations.AddField(
            model_name='operationdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.Product'),
        ),
    ]
