# Generated by Django 2.2.12 on 2021-09-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0071_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='referencia',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Referencia'),
        ),
    ]
