# Generated by Django 2.2.12 on 2021-09-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0072_warehouse_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='referencia',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de Bodega'),
        ),
    ]
