# Generated by Django 2.2.12 on 2021-09-29 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0073_auto_20210929_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriedetail',
            name='cantrec',
        ),
    ]
