# Generated by Django 2.2.12 on 2021-09-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0074_remove_seriedetail_cantrec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='state',
            field=models.CharField(choices=[('Enviado', 'Enviado'), ('Aprobar', 'Aprobar'), ('Anulado', 'Anulado'), ('Aprobado', 'Aprobado'), ('Asignar Series', 'Asignar Series'), ('Rechazado', 'Rechazado'), ('Recibido', 'Recibido')], default='Enviado', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='state',
            field=models.CharField(choices=[('Enviado', 'Enviado'), ('Aprobar', 'Aprobar'), ('Anulado', 'Anulado'), ('Aprobado', 'Aprobado'), ('Asignar Series', 'Asignar Series'), ('Rechazado', 'Rechazado'), ('Recibido', 'Recibido')], default='Enviado', max_length=50),
        ),
        migrations.AlterField(
            model_name='seriedetail',
            name='nuserie',
            field=models.CharField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
